# The right way to do this is to parse xkb files and auto-generate a whole bunch
# of nix files but this is easier.

with (import ./keysyms.nix);

{
  name = "Custom";
  symbols = {
    "${ESC}"  = { symbols = [ Escape ]; };
    "${AE01}" = { symbols = [ "1" exclam ]; };
    "${AE02}" = { symbols = [ "2" at ]; };
    "${AE03}" = { symbols = [ "3" numbersign ]; };
    "${AE04}" = { symbols = [ "4" dollar ]; };
    "${AE05}" = { symbols = [ "5" percent ]; };
    "${AE06}" = { symbols = [ "6" asciicircum ]; };
    "${AE07}" = { symbols = [ "7" ampersand ]; };
    "${AE08}" = { symbols = [ "8" asterisk ]; };
    "${AE09}" = { symbols = [ "9" parenleft ]; };
    "${AE10}" = { symbols = [ "0" parenright ]; };
    "${AE11}" = { symbols = [ minus underscore ]; };
    "${AE12}" = { symbols = [ equal plus ]; };
    "${BKSP}" = { symbols = [ BackSpace BackSpace ]; };
    "${TAB}"  = { symbols = [ Tab ISO_Left_Tab ]; };
    "${AD01}" = { symbols = [ q Q ]; };
    "${AD02}" = { symbols = [ w W ]; };
    "${AD03}" = { symbols = [ e E ]; };
    "${AD04}" = { symbols = [ r R ]; };
    "${AD05}" = { symbols = [ t T ]; };
    "${AD06}" = { symbols = [ y Y ]; };
    "${AD07}" = { symbols = [ u U ]; };
    "${AD08}" = { symbols = [ i I ]; };
    "${AD09}" = { symbols = [ o O ]; };
    "${AD10}" = { symbols = [ p P ]; };
    "${AD11}" = { symbols = [ bracketleft braceleft ]; };
    "${AD12}" = { symbols = [ bracketright braceright ]; };
    "${RTRN}" = { symbols = [ Return ]; };
    "${LCTL}" = { symbols = [ Caps_Lock ]; };
    "${AC01}" = { symbols = [ a A ]; };
    "${AC02}" = { symbols = [ s S ]; };
    "${AC03}" = { symbols = [ d D ]; };
    "${AC04}" = { symbols = [ f F ]; };
    "${AC05}" = { symbols = [ g G ]; };
    "${AC06}" = { symbols = [ h H ]; };
    "${AC07}" = { symbols = [ j J ]; };
    "${AC08}" = { symbols = [ k K ]; };
    "${AC09}" = { symbols = [ l L ]; };
    "${AC10}" = { symbols = [ semicolon colon ]; };
    "${AC11}" = { symbols = [ apostrophe quotedbl ]; };
    "${TLDE}" = { symbols = [ grave asciitilde ]; };
    "${LFSH}" = { symbols = [ Shift_L ]; };
    "${BKSL}" = { symbols = [ backslash bar ]; };
    "${AB01}" = { symbols = [ z Z ]; };
    "${AB02}" = { symbols = [ x X ]; };
    "${AB03}" = { symbols = [ c C ]; };
    "${AB04}" = { symbols = [ v V ]; };
    "${AB05}" = { symbols = [ b B ]; };
    "${AB06}" = { symbols = [ n N ]; };
    "${AB07}" = { symbols = [ m M ]; };
    "${AB08}" = { symbols = [ comma less ]; };
    "${AB09}" = { symbols = [ period greater ]; };
    "${AB10}" = { symbols = [ slash question ]; };
    "${RTSH}" = { symbols = [ Shift_R ]; };
    "${KPMU}" = { type = "CTRL+ALT"; symbols = [ KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86ClearGrab ]; };
    "${LALT}" = { symbols = [ Alt_L Meta_L ]; };
    "${SPCE}" = { symbols = [ space ]; };
    "${CAPS}" = { symbols = [ Control_L ]; };
    "${FK01}" = { type = "PC_ALT_LEVEL2"; symbols = [ F1 XF86Switch_VT_1 ]; };
    "${FK02}" = { type = "PC_ALT_LEVEL2"; symbols = [ F2 XF86Switch_VT_2 ]; };
    "${FK03}" = { type = "PC_ALT_LEVEL2"; symbols = [ F3 XF86Switch_VT_3 ]; };
    "${FK04}" = { type = "PC_ALT_LEVEL2"; symbols = [ F4 XF86Switch_VT_4 ]; };
    "${FK05}" = { type = "PC_ALT_LEVEL2"; symbols = [ F5 XF86Switch_VT_5 ]; };
    "${FK06}" = { type = "PC_ALT_LEVEL2"; symbols = [ F6 XF86Switch_VT_6 ]; };
    "${FK07}" = { type = "PC_ALT_LEVEL2"; symbols = [ F7 XF86Switch_VT_7 ]; };
    "${FK08}" = { type = "PC_ALT_LEVEL2"; symbols = [ F8 XF86Switch_VT_8 ]; };
    "${FK09}" = { type = "PC_ALT_LEVEL2"; symbols = [ F9 XF86Switch_VT_9 ]; };
    "${FK10}" = { type = "PC_ALT_LEVEL2"; symbols = [ F10 XF86Switch_VT_10 ]; };
    "${FK11}" = { type = "PC_ALT_LEVEL2"; symbols = [ F11 XF86Switch_VT_11 ]; };
    "${FK12}" = { type = "PC_ALT_LEVEL2"; symbols = [ F12 XF86Switch_VT_12 ]; };
    "${NMLK}" = { symbols = [ Num_Lock ]; };
    "${SCLK}" = { symbols = [ Scroll_Lock ]; };
    "${KP7}"  = { symbols = [ KP_Home KP_7 ]; };
    "${KP8}"  = { symbols = [ KP_Up KP_8 ]; };
    "${KP9}"  = { symbols = [ KP_Prior KP_9 ]; };
    "${KPSU}" = { type = "CTRL+ALT"; symbols = [ KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode ]; };
    "${KP4}"  = { symbols = [ KP_Left KP_4 ]; };
    "${KP5}"  = { symbols = [ KP_Begin KP_5 ]; };
    "${KP6}"  = { symbols = [ KP_Right KP_6 ]; };
    "${KPAD}" = { type = "CTRL+ALT"; symbols = [ KP_Add KP_Add KP_Add KP_Add XF86Next_VMode ]; };
    "${KP1}"  = { symbols = [ KP_End KP_1 ]; };
    "${KP2}"  = { symbols = [ KP_Down KP_2 ]; };
    "${KP3}"  = { symbols = [ KP_Next KP_3 ]; };
    "${KP0}"  = { symbols = [ KP_Insert KP_0 ]; };
    "${KPDL}" = { symbols = [ KP_Delete KP_Decimal ]; };
    "${LVL3}" = { symbols = [ ISO_Level3_Shift ]; };
    "${MDSW}" = { symbols = [ Mode_switch ]; };
    "${LSGT}" = { type = "FOUR_LEVEL"; symbols = [ less greater bar brokenbar ]; };
    "${KATA}" = { symbols = [ Katakana ]; };
    "${HIRA}" = { symbols = [ Hiragana ]; };
    "${HENK}" = { symbols = [ Henkan_Mode ]; };
    "${HKTG}" = { symbols = [ Hiragana_Katakana ]; };
    "${MUHE}" = { symbols = [ Muhenkan ]; };
    "${KPEN}" = { symbols = [ KP_Enter ]; };
    "${RCTL}" = { symbols = [ Control_R ]; };
    "${KPDV}" = { type = "CTRL+ALT"; symbols = [ KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab ]; };
    "${PRSC}" = { type = "PC_ALT_LEVEL2"; symbols = [ Print Sys_Req ]; };
    "${RALT}" = { type = "TWO_LEVEL"; symbols = [ Alt_R Meta_R ]; };
    "${LNFD}" = { symbols = [ Linefeed ]; };
    "${HOME}" = { symbols = [ Home ]; };
    "${UP}"   = { symbols = [ Up ]; };
    "${PGUP}" = { symbols = [ Prior ]; };
    "${LEFT}" = { symbols = [ Left ]; };
    "${RGHT}" = { symbols = [ Right ]; };
    "${END}"  = { symbols = [ End ]; };
    "${DOWN}" = { symbols = [ Down ]; };
    "${PGDN}" = { symbols = [ Next ]; };
    "${INS}"  = { symbols = [ Insert ]; };
    "${DELE}" = { symbols = [ Delete ]; };
    "${MUTE}" = { symbols = [ XF86AudioMute ]; };
    "${VOLD}" = { symbols = [ XF86AudioLowerVolume ]; };
    "${VOLU}" = { symbols = [ XF86AudioRaiseVolume ]; };
    "${POWR}" = { symbols = [ XF86PowerOff ]; };
    "${KPEQ}" = { symbols = [ KP_Equal ]; };
    "${I126}" = { symbols = [ plusminus ]; };
    "${PAUS}" = { type = "PC_CONTROL_LEVEL2"; symbols = [ Pause Break ]; };
    "${I128}" = { symbols = [ XF86LaunchA ]; };
    "${I129}" = { symbols = [ KP_Decimal KP_Decimal ]; };
    "${HNGL}" = { symbols = [ Hangul ]; };
    "${HJCV}" = { symbols = [ Hangul_Hanja ]; };
    "${AE13}" = { symbols = [ ]; };
    "${LWIN}" = { symbols = [ Super_L ]; };
    "${RWIN}" = { symbols = [ Super_R ]; };
    "${MENU}" = { symbols = [ Menu ]; };
    "${STOP}" = { symbols = [ Cancel ]; };
    "${AGAI}" = { symbols = [ Redo ]; };
    "${PROP}" = { symbols = [ SunProps ]; };
    "${UNDO}" = { symbols = [ Undo ]; };
    "${FRNT}" = { symbols = [ SunFront ]; };
    "${COPY}" = { symbols = [ XF86Copy ]; };
    "${OPEN}" = { symbols = [ XF86Open ]; };
    "${PAST}" = { symbols = [ XF86Paste ]; };
    "${FIND}" = { symbols = [ Find ]; };
    "${CUT}"  = { symbols = [ XF86Cut ]; };
    "${HELP}" = { symbols = [ Help ]; };
    "${I147}" = { symbols = [ XF86MenuKB ]; };
    "${I148}" = { symbols = [ XF86Calculator ]; };
    "${I149}" = { symbols = [ ]; };
    "${I150}" = { symbols = [ XF86Sleep ]; };
    "${I151}" = { symbols = [ XF86WakeUp ]; };
    "${I152}" = { symbols = [ XF86Explorer ]; };
    "${I153}" = { symbols = [ XF86Send ]; };
    "${I154}" = { symbols = [ ]; };
    "${I155}" = { symbols = [ XF86Xfer ]; };
    "${I156}" = { symbols = [ XF86Launch1 ]; };
    "${I157}" = { symbols = [ XF86Launch2 ]; };
    "${I158}" = { symbols = [ XF86WWW ]; };
    "${I159}" = { symbols = [ XF86DOS ]; };
    "${I160}" = { symbols = [ XF86ScreenSaver ]; };
    "${I161}" = { symbols = [ XF86RotateWindows ]; };
    "${I162}" = { symbols = [ XF86TaskPane ]; };
    "${I163}" = { symbols = [ XF86Mail ]; };
    "${I164}" = { symbols = [ XF86Favorites ]; };
    "${I165}" = { symbols = [ XF86MyComputer ]; };
    "${I166}" = { symbols = [ XF86Back ]; };
    "${I167}" = { symbols = [ XF86Forward ]; };
    "${I168}" = { symbols = [ ]; };
    "${I169}" = { symbols = [ XF86Eject ]; };
    "${I170}" = { symbols = [ XF86Eject XF86Eject ]; };
    "${I171}" = { symbols = [ XF86AudioNext ]; };
    "${I172}" = { symbols = [ XF86AudioPlay XF86AudioPause ]; };
    "${I173}" = { symbols = [ XF86AudioPrev ]; };
    "${I174}" = { symbols = [ XF86AudioStop XF86Eject ]; };
    "${I175}" = { symbols = [ XF86AudioRecord ]; };
    "${I176}" = { symbols = [ XF86AudioRewind ]; };
    "${I177}" = { symbols = [ XF86Phone ]; };
    "${I178}" = { symbols = [ ]; };
    "${I179}" = { symbols = [ XF86Tools ]; };
    "${I180}" = { symbols = [ XF86HomePage ]; };
    "${I181}" = { symbols = [ XF86Reload ]; };
    "${I182}" = { symbols = [ XF86Close ]; };
    "${I183}" = { symbols = [ ]; };
    "${I184}" = { symbols = [ ]; };
    "${I185}" = { symbols = [ XF86ScrollUp ]; };
    "${I186}" = { symbols = [ XF86ScrollDown ]; };
    "${I187}" = { symbols = [ parenleft ]; };
    "${I188}" = { symbols = [ parenright ]; };
    "${I189}" = { symbols = [ XF86New ]; };
    "${I190}" = { symbols = [ Redo ]; };
    "${FK13}" = { symbols = [ XF86Tools ]; };
    "${FK14}" = { symbols = [ XF86Launch5 ]; };
    "${FK15}" = { symbols = [ XF86Launch6 ]; };
    "${FK16}" = { symbols = [ XF86Launch7 ]; };
    "${FK17}" = { symbols = [ XF86Launch8 ]; };
    "${FK18}" = { symbols = [ XF86Launch9 ]; };
    "${FK19}" = { symbols = [ ]; };
    "${FK20}" = { symbols = [ XF86AudioMicMute ]; };
    "${FK21}" = { symbols = [ XF86TouchpadToggle ]; };
    "${FK22}" = { symbols = [ XF86TouchpadOn ]; };
    "${FK23}" = { symbols = [ XF86TouchpadOff ]; };
    "${FK24}" = { symbols = [ ]; };
    "${ALT}"  = { symbols = [ NoSymbol Alt_L ]; };
    "${META}" = { symbols = [ NoSymbol Meta_L ]; };
    "${SUPR}" = { symbols = [ NoSymbol Super_L ]; };
    "${HYPR}" = { symbols = [ NoSymbol Hyper_L ]; };
    "${I208}" = { symbols = [ XF86AudioPlay ]; };
    "${I209}" = { symbols = [ XF86AudioPause ]; };
    "${I210}" = { symbols = [ XF86Launch3 ]; };
    "${I211}" = { symbols = [ XF86Launch4 ]; };
    "${I212}" = { symbols = [ XF86LaunchB ]; };
    "${I213}" = { symbols = [ XF86Suspend ]; };
    "${I214}" = { symbols = [ XF86Close ]; };
    "${I215}" = { symbols = [ XF86AudioPlay ]; };
    "${I216}" = { symbols = [ XF86AudioForward ]; };
    "${I217}" = { symbols = [ ]; };
    "${I218}" = { symbols = [ Print ]; };
    "${I219}" = { symbols = [ ]; };
    "${I220}" = { symbols = [ XF86WebCam ]; };
    "${I221}" = { symbols = [ ]; };
    "${I222}" = { symbols = [ ]; };
    "${I223}" = { symbols = [ XF86Mail ]; };
    "${I224}" = { symbols = [ XF86Messenger ]; };
    "${I225}" = { symbols = [ XF86Search ]; };
    "${I226}" = { symbols = [ XF86Go ]; };
    "${I227}" = { symbols = [ XF86Finance ]; };
    "${I228}" = { symbols = [ XF86Game ]; };
    "${I229}" = { symbols = [ XF86Shop ]; };
    "${I230}" = { symbols = [ ]; };
    "${I231}" = { symbols = [ Cancel ]; };
    "${I232}" = { symbols = [ XF86MonBrightnessDown ]; };
    "${I233}" = { symbols = [ XF86MonBrightnessUp ]; };
    "${I234}" = { symbols = [ XF86AudioMedia ]; };
    "${I235}" = { symbols = [ XF86Display ]; };
    "${I236}" = { symbols = [ XF86KbdLightOnOff ]; };
    "${I237}" = { symbols = [ XF86KbdBrightnessDown ]; };
    "${I238}" = { symbols = [ XF86KbdBrightnessUp ]; };
    "${I239}" = { symbols = [ XF86Send ]; };
    "${I240}" = { symbols = [ XF86Reply ]; };
    "${I241}" = { symbols = [ XF86MailForward ]; };
    "${I242}" = { symbols = [ XF86Save ]; };
    "${I243}" = { symbols = [ XF86Documents ]; };
    "${I244}" = { symbols = [ XF86Battery ]; };
    "${I245}" = { symbols = [ XF86Bluetooth ]; };
    "${I246}" = { symbols = [ XF86WLAN ]; };
    "${I247}" = { symbols = [ ]; };
    "${I248}" = { symbols = [ ]; };
    "${I249}" = { symbols = [ ]; };
    "${I250}" = { symbols = [ ]; };
    "${I251}" = { symbols = [ ]; };
    "${I252}" = { symbols = [ ]; };
    "${I253}" = { symbols = [ ]; };
    "${I254}" = { symbols = [ XF86WWAN NoSymbol ]; };
    "${I255}" = { symbols = [ XF86RFKill NoSymbol ]; };
  };
}
